// react/redux/src/main.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'
import { store } from './redux/store.jsx'
import { Provider } from 'react-redux'
ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <Provider store={store}>
    <App />
    </Provider>
  </React.StrictMode>,
)

// react/vue/myproject/src/main.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
// import App from './App.jsx'
import Navbar from './component/Navbar.jsx'
import './index.css'
// import { createApp } from 'vue'
// import App from './App.vue'

createApp(App).mount('#app')

ReactDOM.createRoot(document.getElementById('root')).render(
  // <React.StrictMode>
    <Navbar/>
    // <App />
    
  // </React.StrictMode>,
)
